### ISSUE TITLE
Weeknumber not adhering to ISO standard

### ISSUE THREAD

**Issue by wmeerendonk** [totaldebug/atomic-calendar-revive#1070]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The weeknumber is off by 1 from what is used by ISO standards. I believe either the US or the Islamic system is currently used. See https://www.epochconverter.com/weeks/2023 for reference

### Expected behaviour

I would prefer to have an option where you can select the standard to be used

### Mode

Event (default)

### Card Version

v7.5.0

### Home Assistant Version

2023.6.3

### Configuration

```shell
type: custom:atomic-calendar-revive
entities:
  - calendar.<edited>_gmail_com
  - calendar.verjaardagen
  - calendar.afvalbeheer_mijnafvalwijzer
maxDaysToShow: 12
name: Calendar Card
enableModeChange: true
firstDayOfWeek: 1
refreshInterval: 60
showMultiDay: false
sortByStartTime: true
showMultiDayEventParts: true
showWeekDay: true
hoursOnSameLine: true
hideDuplicates: true
showDate: true
showRelativeTime: false
showCurrentEventLine: false
showWeekNumber: true
showEventIcon: false
showCalendarName: false
calShowDescription: false
showLastCalendarWeek: false
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marksie1988** [comment]
I have checked as I use the dayjs library, this library uses ISO 8601 standard

In the ISO week numbering system:

Week 1 of a year is the week containing the year's first Thursday.
Week 1 might begin in the previous year, and the last few days of a year might belong to the last week of the following year.

**Comment by wmeerendonk** [comment]
![image](https://github.com/totaldebug/atomic-calendar-revive/assets/42252684/7fc7292f-4e1c-4554-967f-0855fff664b2)
Hi, please see attached image of my current view. If you check on https://www.epochconverter.com/weeknumbers  you can see it is off by a week. Let me know If you need something else from me.

**Comment by marksie1988** [comment]
Please could you confirm if this is still an issue with the latest version of the card? 

Im unable to reproduce it but I have made quite a lot of changes to the way dates are handled which may resolve this.

**Comment by wmeerendonk** [comment]
Hi, it is still an issue. Even after updating to 7.7.2 and home assistant
core 2023.9.2. After a fresh restart, the current week (15-9) is listed as
38.

**Comment by marksie1988** [comment]
Could you confirm the country you are from? 

Looking at mine from the UK it shows the correct week number (37)

**Comment by wmeerendonk** [comment]
I live in the Netherlands and can confirm that that is also my country
setting in home assistant. I’m open for a teams session where you can look
at my system if you would like that

**Comment by hostrup** [comment]
Hi! I live in Denmark. 
The week is also shown as +1.
br Ronni

**Comment by marksie1988** [comment]
> Hi! I live in Denmark. The week is also shown as +1. br Ronni

Could you update to 9.0.1-beta.2 and see if that resolves it? 

I just fixed an issue with timezones and I'm not sure if that was the cause.

**Comment by hostrup** [comment]
Hi! Unfortunately it's still showing the current week as Week 41, although it's only week 40 here in DK. 
br Ronni

**Comment by marksie1988** [comment]
Ok tha KS for confirming, I may need to speak to the dayjs community as I get that information with a plugin

**Comment by hostrup** [comment]
let me know i should test it again sometime. br Ronni

**Comment by wmeerendonk** [comment]
I'm no programmer, but was browsing through your codebase. Looking at eventMode.html.ts function getWeekNumberHTML, you call dayjs().week(). There is a function dayjs().isoWeek(). See https://day.js.org/docs/en/plugin/iso-week. Could that help?

**Comment by marksie1988** [comment]
Please could you test the latest beta and see if that setting change resolves the issue?

**Comment by wmeerendonk** [comment]
Using version 9.0.2 beta-1, I now get the correct weeknumbers! Thanks!
