### ISSUE TITLE
Show Event Date and Weekday in same line

### ISSUE THREAD

**Issue by Maetzi87** [totaldebug/atomic-calendar-revive#1160]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

weekday appears _above_ the date, which looks weird in hoursOnSameLine mode
Sun
18

### Expected behaviour

put weekday in left to the date
Sun 18

### Mode

Event (default)

### Context / Reason

First, thank you for the great card!
I use "hoursOnSameLine" to get a compact view, but I would also like to show the weekday _next_ to the event-date on the left side.
At the moment the weekday appears _above_ the date, which looks weird in hoursOnSameLine card. 
Is there a way to put it in front of the date instead?
A solution with cardmodder or a hint how to change the .js file would also be ok, if you don't have time to make a feature.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Maetzi87** [comment]
initial_view: listWeek
type: custom:atomic-calendar-revive
entities:
  - entity: calendar.arzttermine
    icon: mdi:doctor
    color: MediumBlue
  - entity: calendar.privates
    color: DarkViolet
    icon: mdi:account-multiple
  - entity: calendar.thomas
    color: limegreen
    icon: mdi:human-male
  - entity: calendar.events
    color: mediumvioletred
    icon: mdi:party-popper
  - entity: calendar.geburtstage_2
    color: lightseagreen
    icon: mdi:cake-variant
  - entity: calendar.jahrestage
    color: firebrick
    icon: mdi:calendar-month
  - entity: calendar.eva_dienstplan
    color: HotPink
    icon: mdi:briefcase
  - entity: calendar.feiertage_in_osterreich
    color: gold
    icon: mdi:calendar
maxDaysToShow: 7
maxEventCount: 20
showDate: false
showLoader: true
showNoEventsForToday: true
sortByStartTime: true
showNoEventDays: true
showLocation: false
showWeekDay: true
showMultiDayEventParts: true
showRelativeTime: false
hideFinishedEvents: false
showAllDayEvents: true
hoursOnSameLine: true
weekdayOnSameLine: true
refreshInterval: 120
cardHeight: 533px
fullDayEventText: ganztägig
noEventText: keine Termine
compactMode: false
titleLength: 24
showEventDate: true

**Comment by Maetzi87** [comment]
As you can see, I tried nearly all options, I really love this very customizible card, thank you again :-)

**Comment by marksie1988** [comment]
Please could you install `v9.0.0-beta.1` issues around  this should be resolved as part of that. 

Let me know if you have any issues.

**Comment by Maetzi87** [comment]
Hi, sorry for my late answer and thanks for your effort.
But I´m still not absolutely happy with it.
Why is the progress-bar now in the left column with the date? I'd like to have it right under the event, as it was before.
Please move it or tell me how to put it there. Thank you!

**Comment by marksie1988** [comment]
That was a bug, update to latest version and this is fixed

**Comment by Maetzi87** [comment]
I did not say anything 😅🙊

**Comment by herrzettpunkt** [comment]
Could it be that the bugfix no longer allows the weekday and date to be placed underneath each other instead of next to each other?
I use a stack-in card with a mushroom card as a header and now my calendar entries can no longer be properly aligned with the mushroom card. Previously, the weekday and date were underneath each other and I was able to align it perfectly with the calendar symbol at the top with ha-card and adjusting margin-left.
Or is there a way to set the distance between weekday/date and the event?

Now:
![calender](https://github.com/totaldebug/atomic-calendar-revive/assets/89742641/0dba8807-e31c-40c1-be0c-0727f00db397)

Before (Photoshop):
![before](https://github.com/totaldebug/atomic-calendar-revive/assets/89742641/2d399056-bcf1-465e-a48b-f06e4f0787de)
