### ISSUE TITLE
Incorrect calendar item shown (and another missing)

### ISSUE THREAD

**Issue by SebastiaanVBH** [totaldebug/atomic-calendar-revive#1181]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm seeing a full-day item from the previous day as being a past event for today. I'm missing the full-day event for today. My calendar shows:
![image](https://github.com/totaldebug/atomic-calendar-revive/assets/29038179/3ff061fa-c84d-47b0-a26a-465a83df375d)

But the card shows:
![image](https://github.com/totaldebug/atomic-calendar-revive/assets/29038179/e920fedd-0803-4c3b-86c0-72e47edc54f8)

### Expected behaviour

I would expect the first item for today being "Plastic bak buiten"

### Mode

Event (default)

### Card Version

8.0.0

### Home Assistant Version

2023.8.2

### Configuration

```shell
type: custom:atomic-calendar-revive
enableModeChange: true
entities:
  - entity: calendar.meerlanden
    name: Meerlanden
    color: lightcoral
    type: icon
    icon: mdi:delete-sweep-outline
  - entity: calendar.werk
    name: Werk
    color: plum
    type: icon
    icon: mdi:responsive
  - entity: calendar.prive
    name: Privé
    color: cyan
    type: icon
    icon: mdi:home-account
  - entity: calendar.family
    name: Family
    color: lemonchiffon
    type: icon
    icon: mdi:human-male-female-child
  - entity: calendar.homeautomation
    name: HomeAutomation
    type: icon
    icon: mdi:home-assistant
  - entity: calendar.klarinet
    name: Klarinet
    color: lightgreen
    type: icon
    icon: mdi:school-outline
hideFinishedEvents: false
maxDaysToShow: 7
maxEventCount: 11
showDate: true
showMultiDayEventParts: false
showMultiDay: true
compactMode: false
showAllDayEvents: true
offsetHeaderDate: false
allDayBottom: false
showDeclined: false
hideDuplicates: true
hoursOnSameLine: true
descLength: 0
titleLength: 30
showLocation: false
showLastCalendarWeek: false
calShowDescription: false
showCurrentEventLine: false
showWeekDay: true
showMonth: false
showDescription: false
disableLocationLink: false
showNoEventsForToday: true
showEventIcon: true
europeanDate: true
showCalendarName: false
showWeekNumber: false
showDatePerEvent: false
showTimeRemaining: false
startDaysAhead: 0
cardHeight: 100%
defaultMode: Event
dateFormat: LL
showRelativeTime: false
showProgressBar: true
showFullDayProgress: false
showEventDate: true
showAllDayHours: false
showLoader: false
showHiddenText: true
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marksie1988** [comment]
Please could you install `v9.0.0-beta.1` issues around  this should be resolved as part of that. 

Let me know if you have any issues.

**Comment by SebastiaanVBH** [comment]
v9.0.0-beta.1 solves the issue showing the incorrect item from yesterday. But I still don't see the "Plastic bak buiten" I was expecting to see (I saw the item yesterday, so it was loading the correct calendar (calendar.meerlanden)).

I'm using waste_collection_schedule in HACS to get the data. That integration is using Ximmio.nl
When I manually go to Meerlanden, I can download the ICS. This is the part I'm missing (but as you can see, it is showing in the generic HA calendar):

BEGIN:VEVENT
CLASS:PUBLIC
DTEND:20230926T080000
DTSTAMP:20230926T124649Z
DTSTART:20230926T070000
SEQUENCE:0
SUMMARY:PBD / PMD
TRANSP:OPAQUE
UID:b62d5ae1-32ad-4e58-9bc9-070efe5cfe5e
BEGIN:VALARM
ACTION:DISPLAY
DESCRIPTION:Verpakkingen worden vandaag bij u in de buurt opgehaald.
SUMMARY:Verpakkingen worden vandaag bij u in de buurt opgehaald.
TRIGGER:P0D
END:VALARM
END:VEVENT

**Comment by marksie1988** [comment]
Thanks for the feedback, Can you do the following:

1. Press f12
2. Go to network tab
3. Clear it if there is anything in there
4. Refresh the page
5. Look for the entry that is calling the calendar with the missing event
6. You should see the event in the response, please paste it on here 

you can remove sensitive information, the main thing I need to know is 1, that the event is there 2, start and end times/dates etc.

**Comment by SebastiaanVBH** [comment]
[
    {
        "start": {
            "date": "2023-09-29"
        },
        "end": {
            "date": "2023-09-30"
        },
        "summary": "Papier bak buiten",
        "description": null,
        "location": null,
        "uid": null,
        "recurrence_id": null,
        "rrule": null
    },
    {
        "start": {
            "date": "2023-10-03"
        },
        "end": {
            "date": "2023-10-04"
        },
        "summary": "GFT bak buiten",
        "description": null,
        "location": null,
        "uid": null,
        "recurrence_id": null,
        "rrule": null
    }
]

I'm missing the "Plastic bak buiten" event, which should have been today (september 26th).

If I check "Papier bak buiten" in the HA calendar, it is showing as a full-day event on september 29th.

**Comment by SebastiaanVBH** [comment]
The API is requesting:
/api/calendars/calendar.meerlanden?start=2023-09-26T00:00:00Z&end=2023-10-02T23:59:59Z

It is a 2-weekly recurring event, although the original ICS has them as seperate events.

**Comment by marksie1988** [comment]
Ok this was a bug with home assistant a while back, I know there are still some users reporting this issue. See here: https://github.com/home-assistant/core/issues/40127

I'm not sure I can do anything about this as the rest API isn't returning the event.

**Comment by SebastiaanVBH** [comment]
Thank you for checking.

I'm using this as a workaround (I rather see extra items from yesterday than missing items from today):

startDaysAhead: -1

**Comment by kaizersoje** [comment]
> Thank you for checking.
> 
> I'm using this as a workaround (I rather see extra items from yesterday than missing items from today):
> 
> startDaysAhead: -1

I had the same issue as well and had to use this workaround.
