### ISSUE TITLE
Combining maxDaysToShow, maxEventCount and showNoEventDays does not work as expected

### ISSUE THREAD

**Issue by vandernorth** [totaldebug/atomic-calendar-revive#1247]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://github.com/totaldebug/atomic-calendar-revive/assets/5212402/8f907f85-6789-4492-8c5a-2f4563f19a14)

Relevant config:
```
maxDaysToShow: 5
maxEventCount: 1 # would normally be more, but is better for this bug report
showNoEventDays: true
showHiddenText: true
noEventText: NO EVENTS
hiddenEventText: HIDDEN EVENTS
```

When combining these settings: Days that have events filtered out because it goes over the `maxEventCount` will show as "No events".

### Expected behaviour

I would expect one of:
 1) These days not to be shown at all (because the settings is called MAXdaysToShow)
 2) These days to show HIDDEN EVENTS

I would prefer option 1.

### Steps To Reproduce

v9.1.0 on HASS 2023.10.0

Use the above config to reproduce, play with `maxEventCount` a bit.

### Mode

Event (default)

### Card Version

9.1.0

### Home Assistant Version

2023.10.0

### Configuration

```shell
maxDaysToShow: 5
maxEventCount: 1
showNoEventDays: true
showHiddenText: true
noEventText: NO EVENTS
hiddenEventText: HIDDEN EVENTS
```

### Relevant log output

```shell
None
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vandernorth** [comment]
I did.

**Comment by Tosko4** [comment]
I have the same issue, when I say maxDaysToShow: 14 the list is quite long, when i combine it with maxEventCount: 8, it does not show the calendar items of tomorrow.

**Comment by johnekarlsson** [comment]
Same issue for me. The more I increase maxDaysToShow, the more events are skipped, (although always considering the maxEventCount). The selection of what events are shown is not chronological, as expected, but seemingly random.

**Comment by marksie1988** [comment]
Ok so the hidden event text not showing was due to it accidentally being removed at some point when code was re-structured. I have now added that back in so at least you know events are hidden. the issue with the way hidden events is calculated is that its not per day, it counts the total events that were removed from the list of events when limits are applied. This means that although it will tell you `x events hidden` it wont tell you how many on which day. 

I could look at modifying the "No Events" so that it doesnt show when there are hidden events?

**Comment by marksie1988** [comment]
I have released a new beta that fixes the hidden events text [v9.2.1-beta.3](https://github.com/totaldebug/atomic-calendar-revive/releases/tag/v9.2.1-beta.3)

**Comment by johnekarlsson** [comment]
Hi! I have updated to beta.4 now and the issue still persists of seemingly random events being hidden. I'd be glad to assist in troubleshooting or answering questions if there are any!

**Comment by marksie1988** [comment]
@johnekarlsson do you have a copy of your config so I can check if it's something specific with the way you have the config. 

I'm not sure why the events hidden would be random as it takes the current day + `startDaysAhead` + `maxDaysToShow` it then pulls all the events between this sorts them in the order selected and then removes X number of events from the bottom of the list. 

As it removes the events at the end it should always be consistent. The only thing that would amend this is if an event finished as then it would be moved to the end of the list which would mean it would be hidden and one of the events that hasn't finished would be shown.

**Comment by johnekarlsson** [comment]
Here you go!

With the config below I get these events:
<img width="48" alt="image" src="https://github.com/totaldebug/atomic-calendar-revive/assets/63417088/917db93d-246a-4446-9e22-56d9ec028ac4">


But if I remove "maxDaysToShow: 30" I can now see three events that were hidden before (two the 15th and one the 17th).

<img width="50" alt="image" src="https://github.com/totaldebug/atomic-calendar-revive/assets/63417088/139a3c1c-b0a6-49c2-92d8-112a7945827e">



```
type: custom:atomic-calendar-revive
entities:
  - entity: calendar.xxxxxx
    titleColor: red
name: null
enableModeChange: true
firstDayOfWeek: 1
maxDaysToShow: 30
showNoEventsForToday: false
showLastCalendarWeek: false
showProgressBar: false
disableLocationLink: false
showFullDayProgress: false
europeanDate: true
showEventIcon: false
showHiddenText: false
showLoader: false
showDate: false
sortByStartTime: false
hideFinishedEvents: true
showLocation: false
showRelativeTime: false
fullDayEventText: Hela dagen
untilText: till
noEventsForNextDaysText: Inga aktiviteter de kommande dagarna
noEventText: Inga aktiviteter idag
calShowDescription: false
disableCalEventLink: true
disableCalLocationLink: true
disableCalLink: true
dimFinishedEvents: true
disableEventLink: true
showWeekDay: false
language: sv
showMonth: true
showCurrentEventLine: false
maxEventCount: 6
```

**Comment by marksie1988** [comment]
Ok thanks I'll do some testing tomorrow,

How many events are on each of those days? And are there any full day events or are they all timed events? 

This will allow me to totally replicate your expected view Vs the incorrect view.

**Comment by vandernorth** [comment]
Using v9.4.0 the issue seems to be resolved. at least for what is was trying to do.
[johnekarlsson](https://github.com/johnekarlsson) everything working on your end as well?

**Comment by marksie1988** [comment]
I'm working on a fix after I realised what I was doing wrong... 

The all day events were being placed at the begining of the array, but the regular events on the same dates were being pushed down. 

I'm now reworking the logic so that each day is sorted individually and then all merged into one at the end which should solve this.

**Comment by johnekarlsson** [comment]
It works! All issues resolved. Thanks' alot!

Den tis 23 jan. 2024 kl 10:36 skrev Steven Marks ***@***.***>:
