### ISSUE TITLE
finished Events are not sorted correctly 

### ISSUE THREAD

**Issue by sevorl** [totaldebug/atomic-calendar-revive#1258]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Finished events used to be at the top of the event list when "softBy: start"
This is no longer the case.

Instead, the finished events are "somewhere" in the list 
See screenshot, finished Events are dimmed
<img width="327" alt="image" src="https://github.com/totaldebug/atomic-calendar-revive/assets/81764300/c1538d80-ac77-4478-a160-5ae7912c2c04">

### Expected behaviour

Finished Events should be at the top of the list

### Steps To Reproduce

display a calendar with the configuration I pasted in "Configuration".
 

### Mode

Event (default)

### Card Version

v.9.2.0

### Home Assistant Version

2023.10

### Configuration

```shell
type: custom:atomic-calendar-revive
enableModeChange: true
entities:
  - entity: calendar.stundenplan_jakob
    name: Stundenplan Jakob
    blocklist: (Pause)|(Sport)|(Schwimmen)

firstDayOfWeek: 1
descLength: 10
defaultMode: Event
hideFinishedEvents: false
showRelativeTime: false
showLocation: false
sortByStartTime: true
showDate: false
hideDuplicates: true
europeanDate: true
showCurrentEventLine: true
showMonth: false
showProgressBar: true
showWeekDay: true
disableEventLink: true
showNoEventsForToday: false
showNoEventDays: true
showFullDayProgress: false
ShowDescription: false
showLastCalendarWeek: false
showEventIcon: false
dimFinishedEvents: true
showHiddenText: false
showDescription: false
untilText: bis
noEventText: Keine Schule
noEventsForTodayText: Nichts mehr zu tun. Auch schön
showLoader: false
noEventsForNextDaysText: Keine Termine in den nächsten Tagen
fullDayEventText: ' '
softLimit: true
maxDaysToShow: 8
calShowDescription: false
eventTitleSize: 100
refreshInterval: 120
dateFormat: dddd, D. MMMM
cardHeight: calc(100vh - 15em)
disableCalLink: true
hoursOnSameLine: true
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sevorl** [comment]
I was able to boil this down to a much simpler configuration 
See screenshot.
<img width="735" alt="image" src="https://github.com/totaldebug/atomic-calendar-revive/assets/81764300/787bb2a2-a496-4bc1-9bd1-fb18401af84e">

It seams like the finished events are sorted backwards.

I removed all configuration except the bare minimum: 


type: custom:atomic-calendar-revive
enableModeChange: true
entities:
  - entity: calendar.stundenplan_jakob
    name: Stundenplan Jakob

**Comment by Xento** [comment]
I think I have the same issue:

![image](https://github.com/totaldebug/atomic-calendar-revive/assets/1299397/98efd5a4-34e9-491f-8f25-3756086f944f)

**Comment by marksie1988** [comment]
Please upgrade to the latest beta, [v9.2.1-beta.1](https://github.com/totaldebug/atomic-calendar-revive/releases/tag/v9.2.1-beta.1) I think this will be fixed as part of #1248, I will also test to confirm

**Comment by marksie1988** [comment]
Ok done a test and still doesnt seem to fix it, i will take a look at this soon to resolve in next beta.

**Comment by sevorl** [comment]
I did a test as well, and for me v9.2.1-beta.1 does fix the issue.
But, I noticed that `allDayBottom: true` has an effect for events that are not all-day-events.
If I set allDayBottom: true, the past events of the day are at the bottom, even if they are not "all-day-events".

If allDayBottom:false, the past events show on top, as expected.

**Comment by ajobbins** [comment]
Confirming the same issue and that v9.2.1-beta.1 didn't resolve it

**Comment by remcodj** [comment]
Same here on HA 2023.11.1 and Atomic Calendar Revive 9.2.0

**Comment by sevorl** [comment]
any update on this?

**Comment by j0dan** [comment]
Seems to be broken since 9.0.2

**Comment by marksie1988** [comment]
Hi All, 

I have just released a new beta, my testing shows this as resolved, please let me know your outcome

**Comment by sevorl** [comment]
Hi marksie, I just installed v9.2.1-beta.2.
Unfortumately, the issue remains. It does not seem to be fixed yet.

**Comment by sevorl** [comment]
Here is a screenshot:
<img width="368" alt="image" src="https://github.com/totaldebug/atomic-calendar-revive/assets/81764300/0d1663ba-ba60-4a51-80fd-9e816b376122">

**Comment by sevorl** [comment]
This is still not resolved. This issue is still open, sorting is not correct. past items are at the bottom, current items are on top.

**Comment by marksie1988** [comment]
Yes that is correct, I had put some code in the wrong area, moved that in the latest and will do a beta release shortly

**Comment by sevorl** [comment]
just tested in v9.3.0-beta.3. Looking good now!
Thanks for all the effort you put into this great calendar!
