### ISSUE TITLE
Using maxEventCount with (only) all day events drops the wrong events

### ISSUE THREAD

**Issue by m-idler** [totaldebug/atomic-calendar-revive#1338]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have a calendar that contains only fall day events of national holidays here in germany ( `http://i.cal.to/ical/65/bayern/feiertage/ef570601.d382ba80-b11081be.ics` ). As I only want to see the next e.g. 3 upcoming holidays, I'm using (`maxDaysToShow: 180` and `maxEventCount: 3`).
After debugging i little bit through the code, it seems the the already correctly sorted events are mixed up and finally the wrong events get dropped...

Current Output (with `maxEventCount: 3`):
![Screenshot 2023-12-28 at 23 01 24](https://github.com/totaldebug/atomic-calendar-revive/assets/2026873/7956c4bf-dd19-4cd4-a226-a103df6c86b6)

Current Output (without `maxEventCount`):
![Screenshot 2023-12-28 at 23 03 10](https://github.com/totaldebug/atomic-calendar-revive/assets/2026873/d4d1ed02-1d6a-4915-8a7f-a214568c485b)

### Expected behaviour

I would expect that the events will be limited according the expected sort order

### Steps To Reproduce

Sorting in https://github.com/totaldebug/atomic-calendar-revive/blob/5b70a35bc170906c0d6eb572d263b129fde80152/src/functions/sort_events.ts#L33 is done as expected (as of today it's 8 events in the correct order based on event start

afterwards the all day events get into reverse order in https://github.com/totaldebug/atomic-calendar-revive/blob/5b70a35bc170906c0d6eb572d263b129fde80152/src/functions/sort_events.ts#L42 due to the decrementing loop

and then the all day events get reordered here, now they aren't ordered by start time anymore: https://github.com/totaldebug/atomic-calendar-revive/blob/5b70a35bc170906c0d6eb572d263b129fde80152/src/functions/sort_events.ts#L48
(as I'm not to deep in all the details of the code and especially this all day event sorting, I'm not sure whether there is also a typo in https://github.com/totaldebug/atomic-calendar-revive/blob/5b70a35bc170906c0d6eb572d263b129fde80152/src/functions/sort_events.ts#L50 , comparing `entity_id` with `entity`?

and finally those reordered all day events go back into the events list in that new order here:
https://github.com/totaldebug/atomic-calendar-revive/blob/5b70a35bc170906c0d6eb572d263b129fde80152/src/functions/sort_events.ts#L63

### Mode

Both

### Card Version

9.2.1

### Home Assistant Version

2023.12.4

### Configuration

```shell
type: custom:atomic-calendar-revive
name: Feiertage
enableModeChange: true
entities:
  - entity: calendar.feiertage
    showMultiDay: true
    maxDaysToShow: 180
disableCalLink: true
disableCalLocationLink: true
disableCalEventLink: true
showDescription: false
showWeekDay: true
showMonth: true
disableEventLink: true
showCalendarName: true
maxDaysToShow: 180
maxEventCount: 3
showLocation: false
showRelativeTime: false
europeanDate: true
showHiddenText: false
showAllDayHours: false
offsetHeaderDate: false
showProgressBar: false
dimFinishedEvents: true
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by h3rbst** [comment]
I have this problem as well. Any workaround?

**Comment by Pscharumbel** [comment]
Same. Still with 9.3.0.

**Comment by marksie1988** [comment]
This should now be resolved on the latest Beta, Please test and let me know how it works out then I will release.

**Comment by Pscharumbel** [comment]
Hi!

Thanks for your work! Unfortunately, the error persists despite the beta, as soon as I remove maxDaysToShow.

**Comment by h3rbst** [comment]
For me it is not working with Beta 3 as well :(

**Comment by marksie1988** [comment]
@h3rbst what are you seeing that is incorrect? 

Have you made sure the old version of the card is still not cached?

**Comment by marksie1988** [comment]
> Hi!
> 
> Thanks for your work! Unfortunately, the error persists despite the beta, as soon as I remove maxDaysToShow.

What are you seeing that is incorrect as I cant replicate an issue with all day events being in the wrong order anymore? 

Do you have a copy of your card config that could assist me in testing?

**Comment by h3rbst** [comment]
> @h3rbst what are you seeing that is incorrect?
> 
> Have you made sure the old version of the card is still not cached?

I am sure, that cache is cleared, yes.
Here you see the configuration, how it looks like and what the calendar looks like.
E.g. the dates of 25.03. and 28.03. are missing.
With maxDaysToShow: 14 they are shown.
<img width="359" alt="Bildschirmfoto 2024-01-15 um 14 42 04" src="https://github.com/totaldebug/atomic-calendar-revive/assets/79704794/b6f9482d-790b-498f-aa3a-87767f10e072">
<img width="506" alt="Bildschirmfoto 2024-01-15 um 14 43 27" src="https://github.com/totaldebug/atomic-calendar-revive/assets/79704794/b5c462df-945d-471f-b7b1-28ff03e6dbf8">
<img width="1002" alt="Bildschirmfoto 2024-01-15 um 14 44 00" src="https://github.com/totaldebug/atomic-calendar-revive/assets/79704794/5f505b32-2945-45ae-b747-e535ef5dc16e">

**Comment by marksie1988** [comment]
@h3rbst ok and those events are from a different calendar?

**Comment by marksie1988** [comment]
Ok thanks ill look into that, I only tested across one of my calendars so will test with two now

**Comment by Pscharumbel** [comment]
Yes, I also have multiple calendars. 😃

**Comment by marksie1988** [comment]
I have done more testing this morning and im unable to reproduce an issue with the sorting since adding the fix: 

![image](https://github.com/totaldebug/atomic-calendar-revive/assets/159166/2a0ae0e0-6691-4e36-9678-210c2e56231b)

**Comment by Pscharumbel** [comment]
Thank you very much!
